[package]
name = "apexdumper"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "libapexdumper"

[profile.release]
debug = false

[dependencies]
pelite = "0.10"
fmtools = "0.1"
dataview = "1.0"
